"""Add plan models

Revision ID: 3ffed3707880
Revises: e707419bbfc1
Create Date: 2026-04-02 15:24:36.986772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '3ffed3707880'
down_revision: Union[str, Sequence[str], None] = 'e707419bbfc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('result_ref', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_table('career_path_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('paths', sa.JSON(), nullable=True),
    sa.Column('rejected_paths', sa.JSON(), nullable=True),
    sa.Column('selected_path_id', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_path_sets_id'), 'career_path_sets', ['id'], unique=False)
    op.create_table('salary_bridges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('career_path_set_id', sa.Integer(), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('outputs', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['career_path_set_id'], ['career_path_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_bridges_id'), 'salary_bridges', ['id'], unique=False)
    op.create_table('roadmaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salary_bridge_id', sa.Integer(), nullable=False),
    sa.Column('timeline_months', sa.Integer(), nullable=False),
    sa.Column('phases', sa.JSON(), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['salary_bridge_id'], ['salary_bridges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmaps_id'), 'roadmaps', ['id'], unique=False)
    op.create_table('scenario_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roadmap_id', sa.Integer(), nullable=False),
    sa.Column('modified_inputs', sa.JSON(), nullable=False),
    sa.Column('deterministic_out', sa.JSON(), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_runs_id'), 'scenario_runs', ['id'], unique=False)
    op.add_column('profiles', sa.Column('raw_input', sa.Text(), nullable=True))
    op.add_column('profiles', sa.Column('structured', sa.JSON(), nullable=True))
    op.add_column('profiles', sa.Column('confidence_scores', sa.JSON(), nullable=True))
    op.add_column('profiles', sa.Column('prompt_version', sa.Text(), nullable=True))
    op.drop_column('profiles', 'raw_data')
    op.drop_column('profiles', 'structured_data')
    op.add_column('users', sa.Column('hashed_password', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('plan', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'plan')
    op.drop_column('users', 'hashed_password')
    op.add_column('profiles', sa.Column('structured_data', sqlite.JSON(), nullable=True))
    op.add_column('profiles', sa.Column('raw_data', sqlite.JSON(), nullable=True))
    op.drop_column('profiles', 'prompt_version')
    op.drop_column('profiles', 'confidence_scores')
    op.drop_column('profiles', 'structured')
    op.drop_column('profiles', 'raw_input')
    op.drop_index(op.f('ix_scenario_runs_id'), table_name='scenario_runs')
    op.drop_table('scenario_runs')
    op.drop_index(op.f('ix_roadmaps_id'), table_name='roadmaps')
    op.drop_table('roadmaps')
    op.drop_index(op.f('ix_salary_bridges_id'), table_name='salary_bridges')
    op.drop_table('salary_bridges')
    op.drop_index(op.f('ix_career_path_sets_id'), table_name='career_path_sets')
    op.drop_table('career_path_sets')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
